-- MySQL Script generated by MySQL Workbench
-- Sex 04 Nov 2016 09:27:56 BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema escala_web
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escala_web
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escala_web` DEFAULT CHARACTER SET utf8 ;
USE `escala_web` ;

-- -----------------------------------------------------
-- Table `escala_web`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escala_web`.`pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escala_web`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escala_web`.`grupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escala_web`.`jornada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escala_web`.`jornada` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hora_inicio` DATETIME NOT NULL,
  `hora_fim` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escala_web`.`escala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escala_web`.`escala` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dia` INT NOT NULL,
  `mes` INT NOT NULL,
  `ano` INT NOT NULL,
  `observacao` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escala_web`.`pessoa_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escala_web`.`pessoa_grupo` (
  `grupo_id` INT NOT NULL,
  `pessoa_id` INT NOT NULL,
  PRIMARY KEY (`grupo_id`, `pessoa_id`),
  INDEX `fk_grupo_pessoa` (`pessoa_id` ASC),
  INDEX `fk_pessoa_grupo` (`grupo_id` ASC),
  CONSTRAINT `fk_pessoa_grupo`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `escala_web`.`grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_pessoa`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `escala_web`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escala_web`.`escala_jornada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escala_web`.`escala_jornada` (
  `escala_id` INT NOT NULL,
  `jornada_id` INT NOT NULL,
  PRIMARY KEY (`escala_id`, `jornada_id`),
  INDEX `fk_escala_jornada` (`jornada_id` ASC),
  INDEX `fk_jornada_escala` (`escala_id` ASC),
  CONSTRAINT `fk_jornada_escala`
    FOREIGN KEY (`escala_id`)
    REFERENCES `escala_web`.`escala` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escala_jornada`
    FOREIGN KEY (`jornada_id`)
    REFERENCES `escala_web`.`jornada` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escala_web`.`pessoa_escala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escala_web`.`pessoa_escala` (
  `pessoa_id` INT NOT NULL,
  `escala_id` INT NOT NULL,
  `jornada_id` INT NOT NULL,
  PRIMARY KEY (`pessoa_id`, `escala_id`, `jornada_id`),
  INDEX `fk_jornada_pessoa` (`escala_id` ASC, `jornada_id` ASC),
  INDEX `fk_pessoa_jornada` (`pessoa_id` ASC),
  CONSTRAINT `fk_jornada_pessoa`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `escala_web`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_jornada`
    FOREIGN KEY (`escala_id` , `jornada_id`)
    REFERENCES `escala_web`.`escala_jornada` (`escala_id` , `jornada_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
