-- MySQL Script generated by MySQL Workbench
-- Ter 01 Nov 2016 16:23:00 BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema escala_mesce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escala_mesce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escala_mesce` DEFAULT CHARACTER SET utf8 ;
USE `escala_mesce` ;

-- -----------------------------------------------------
-- Table `escala_mesce`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escala_mesce`.`pessoa` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `email` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escala_mesce`.`escala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escala_mesce`.`escala` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dia` INT NOT NULL,
  `mes` INT NOT NULL,
  `ano` INT NOT NULL,
  `horario` DATETIME NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escala_mesce`.`pessoa_escala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escala_mesce`.`pessoa_escala` (
  `id_pessoa` INT UNSIGNED NOT NULL,
  `id_escala` INT NOT NULL,
  INDEX `fk_pessoa_escala` (`id_pessoa` ASC),
  INDEX `fk_escala_pessoa` (`id_escala` ASC),
  CONSTRAINT `fk_pessoa_escala`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `escala_mesce`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escala_pessoa`
    FOREIGN KEY (`id_escala`)
    REFERENCES `escala_mesce`.`escala` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
