-- MySQL Script generated by MySQL Workbench
-- Seg 07 Nov 2016 15:22:16 BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema escala_web
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `escala_web` ;

-- -----------------------------------------------------
-- Schema escala_web
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escala_web` DEFAULT CHARACTER SET utf8 ;
USE `escala_web` ;

-- -----------------------------------------------------
-- Table `escala_web`.`coordenador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escala_web`.`coordenador` ;

CREATE TABLE IF NOT EXISTS `escala_web`.`coordenador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escala_web`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escala_web`.`pessoa` ;

CREATE TABLE IF NOT EXISTS `escala_web`.`pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `coordenador_id` INT NOT NULL,
  PRIMARY KEY (`id`, `coordenador_id`),
  INDEX `fk_pessoa_coordenador` (`coordenador_id` ASC),
  CONSTRAINT `fk_pessoa_coordenador`
    FOREIGN KEY (`coordenador_id`)
    REFERENCES `escala_web`.`coordenador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escala_web`.`grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escala_web`.`grupo` ;

CREATE TABLE IF NOT EXISTS `escala_web`.`grupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `coordenador_id` INT NOT NULL,
  PRIMARY KEY (`id`, `coordenador_id`),
  INDEX `fk_grupo_coordenador` (`coordenador_id` ASC),
  CONSTRAINT `fk_grupo_coordenador`
    FOREIGN KEY (`coordenador_id`)
    REFERENCES `escala_web`.`coordenador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escala_web`.`jornada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escala_web`.`jornada` ;

CREATE TABLE IF NOT EXISTS `escala_web`.`jornada` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hora_inicio` TIME NOT NULL,
  `hora_fim` TIME NULL,
  `coordenador_id` INT NOT NULL,
  `descricao` VARCHAR(200) NULL,
  PRIMARY KEY (`id`, `coordenador_id`),
  INDEX `fk_jornada_coordenador` (`coordenador_id` ASC),
  CONSTRAINT `fk_jornada_coordenador`
    FOREIGN KEY (`coordenador_id`)
    REFERENCES `escala_web`.`coordenador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escala_web`.`escala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escala_web`.`escala` ;

CREATE TABLE IF NOT EXISTS `escala_web`.`escala` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NULL,
  `grupo_id` INT NOT NULL,
  `coordenador_id` INT NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `observacao` LONGTEXT NULL,
  PRIMARY KEY (`id`, `grupo_id`, `coordenador_id`),
  INDEX `fk_escala_grupo` (`grupo_id` ASC),
  INDEX `fk_escala_coordenador` (`coordenador_id` ASC),
  CONSTRAINT `fk_escala_grupo`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `escala_web`.`grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escala_coordenador`
    FOREIGN KEY (`coordenador_id`)
    REFERENCES `escala_web`.`coordenador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escala_web`.`pessoa_grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escala_web`.`pessoa_grupo` ;

CREATE TABLE IF NOT EXISTS `escala_web`.`pessoa_grupo` (
  `grupo_id` INT NOT NULL,
  `pessoa_id` INT NOT NULL,
  PRIMARY KEY (`grupo_id`, `pessoa_id`),
  INDEX `fk_grupo_pessoa` (`pessoa_id` ASC),
  INDEX `fk_pessoa_grupo` (`grupo_id` ASC),
  CONSTRAINT `fk_pessoa_grupo`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `escala_web`.`grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_pessoa`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `escala_web`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escala_web`.`escala_jornada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escala_web`.`escala_jornada` ;

CREATE TABLE IF NOT EXISTS `escala_web`.`escala_jornada` (
  `escala_id` INT NOT NULL,
  `jornada_id` INT NOT NULL,
  `dia` INT NOT NULL,
  `mes` INT NOT NULL,
  `ano` INT NOT NULL,
  PRIMARY KEY (`escala_id`, `jornada_id`, `dia`, `mes`, `ano`),
  INDEX `fk_escala_jornada` (`jornada_id` ASC),
  INDEX `fk_jornada_escala` (`escala_id` ASC),
  CONSTRAINT `fk_jornada_escala`
    FOREIGN KEY (`escala_id`)
    REFERENCES `escala_web`.`escala` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escala_jornada`
    FOREIGN KEY (`jornada_id`)
    REFERENCES `escala_web`.`jornada` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escala_web`.`pessoa_escala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escala_web`.`pessoa_escala` ;

CREATE TABLE IF NOT EXISTS `escala_web`.`pessoa_escala` (
  `pessoa_id` INT NOT NULL,
  `escala_id` INT NOT NULL,
  `jornada_id` INT NOT NULL,
  `dia` INT NOT NULL,
  `mes` INT NOT NULL,
  `ano` INT NOT NULL,
  PRIMARY KEY (`pessoa_id`, `escala_id`, `jornada_id`, `dia`, `mes`, `ano`),
  INDEX `fk_pessoa_jornada` (`pessoa_id` ASC),
  INDEX `fk_pessoa_escala_idx` (`escala_id` ASC, `jornada_id` ASC, `dia` ASC, `mes` ASC, `ano` ASC),
  CONSTRAINT `fk_pessoa_jornada`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `escala_web`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_escala`
    FOREIGN KEY (`escala_id` , `jornada_id` , `dia` , `mes` , `ano`)
    REFERENCES `escala_web`.`escala_jornada` (`escala_id` , `jornada_id` , `dia` , `mes` , `ano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


insert into coordenador (nome, email, senha) values ('john', 'johanessevero@gmail.com', '123');

insert into pessoa (nome, email, coordenador_id) values ('JOHANES', 'johanessevero@gmail.com', 1);
insert into pessoa (nome, email, coordenador_id) values ('SANDRA', 'sandricamv@gmail.com', 1);

insert into grupo (nome, coordenador_id) values ('MESCE', 1);

insert into pessoa_grupo (pessoa_id, grupo_id) values (1, 1);
insert into pessoa_grupo (pessoa_id, grupo_id) values (1, 2);

insert into jornada (hora_inicio, hora_fim, descricao, coordenador_id) values ('08:00','09:30','missa das 8',1);
insert into jornada (hora_inicio, hora_fim, descricao, coordenador_id) values ('09:00','10:30','missa - 1º sábado do mes',1);
insert into jornada (hora_inicio, hora_fim, descricao, coordenador_id) values ('10:00','11:30','missa das 10',1);
insert into jornada (hora_inicio, hora_fim, descricao, coordenador_id) values ('16:00','17:30','missa da catequese',1);
insert into jornada (hora_inicio, hora_fim, descricao, coordenador_id) values ('19:00','20:30','missa do sábado',1);
insert into jornada (hora_inicio, hora_fim, descricao, coordenador_id) values ('19:30','21:00','missa da semana',1);
insert into jornada (hora_inicio, hora_fim, descricao, coordenador_id) values ('20:30','22:00','adoração de quinta',1);
insert into jornada (hora_inicio, hora_fim, descricao, coordenador_id) values ('20:30','22:00','reunião dos mesce',1);

